# Generated by Django 5.2 on 2025-05-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('moisture', models.FloatField(blank=True, null=True)),
                ('ph_level', models.FloatField(blank=True, null=True)),
                ('temperature_status', models.CharField(blank=True, max_length=20)),
                ('humidity_status', models.CharField(blank=True, max_length=20)),
                ('moisture_status', models.CharField(blank=True, max_length=20)),
                ('ph_status', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
